capos/capos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

capos/index/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index)
]

capos/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('changes', views.changes, name='changes'),
    path('contacts', views.contacts, name='contacts')
]

capos/main/models.py
from django.db import models

class Audio(models.Model):
    audiofile = models.FileField("Аудиофайл", upload_to="audiofiles")

    def __str__(self):
        return(str(self.audiofile))
    
    

capos/main/forms.py
from django import forms
from django.forms import ModelForm, FileInput
from .models import Audio


class AudioForm(ModelForm):
    class Meta:
        model = Audio
        fields = ["audiofile"] 
        widgets = {
            "audiofile" : FileInput(attrs={
                "accept" : ".wav"
            })
        }

capos/main/views.py
import os
import re
from docx import Document
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from .forms import AudioForm
from .models import Audio
from .transcriber import transcribe


def index(request):
    if request.method == "POST":
        form = AudioForm(request.POST, request.FILES)
        if form.is_valid():
            file = Audio(audiofile=request.FILES['audiofile'])
            file_name = str(file)
            file.save()
            text = transcribe(str(file))
            os.remove(str(f"{settings.MEDIA_ROOT}/{file}"))
            doc = Document()
            doc.add_paragraph(text.lower())
            file.delete()
            response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document')
            response['Content-Disposition'] = f'attachment; filename={file_name}_transcribed.docx'
            doc.save(response)

            return response
    else:
        form = AudioForm()
    return render(request, 'main/index.html', {'form': form})

def changes(request):
    return render(request, 'main/changes.html')

def contacts(request):
    return render(request, 'main/contacts.html')

capos/main/templates/main/base.html
<!DOCTYPE html>
<html lang="ru">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Custom style -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'main/main.css' %}">
    </head>


    <body>
        <nav class="navbar navbar-fixed-top navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'home' %}">CAPOS</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'home' %}">Главная</a></li>
                        <li><a href="{% url 'changes' %}">Изменения</a></li>
                        <li><a href="{% url 'contacts' %}">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </nav>

            <div class="container">

                {% block main %}{% endblock %}

                <hr>

                <footer>
                    <p>&copy; 2021 Merul Group</p>
                </footer>

            </div>
    </body>

</html>

capos/main/templates/main/changes.html
{% extends 'main/base.html' %}


{% block title %}
    Главная страница
{% endblock %}


{% block main %}
    Здесь должны быть изменения
{% endblock %}

capos/main/templates/main/contacts.html
{% extends 'main/base.html' %}


{% block title %}
    Главная страница
{% endblock %}


{% block main %}
    Здесь должны быть контакты
{% endblock %}

capos/main/templates/main/index.html
{% extends 'main/base.html' %}


{% block title %}
    Главная страница
{% endblock %}


{% block main %}
    <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12">
            <div class="jumbotron">
                <div>
                    <b>CAPOS</b> (<b>C</b>onferences <b>a</b>uto-<b>p</b>rotocoling <b>o</b>nline <b>s</b>ystem) - это веб-интерфейс, предназначенный для преобразования аудиофайла в документ. Результатом обработки CAPOS является текстовый файл стенограммы конференции, который максимально удобен для понимания и анализа информации.
                    <br>
                    Главные особенности веб-интерфейса:
                    <br>
                    1.Процесс преобразование аудиофайла автоматический, что, в свою очередь, предполагает возможность выполнения пользователем несколько задач одновременно.
                    <br>
                    2.После успешного преобразования первичный файл удаляется, а значит и нагрузка на сервер существенно снижается.
                    <br>
                    3.Система авто-протоколирования основана на общедоступных библиотеках, что позволяет эксплуатировать веб-интерфейс абсолютно бесплатно.
                    <br>
                    4.Аудиофайлы, загружаемые в систему, не имеют ограничений по длительности. 
                </div>
                <br>
                <form form enctype="multipart/form-data" method="post" action="/">
                    {% csrf_token %}
                    <div class="form-group">
                      <label class="custom-file" for="id_audiofile">
                        {{ form.audiofile }}
                        <span class="custom-file-control">
                            Выберите аудиофайл
                        </span>
                      </label>
                    </div>

                    <button type="submit" class="btn btn-primary">
                        Транскрибировать файл
                    </button>
                    <br>
                    <small id="fileHelpId" class="form-text text-muted">На данный момент поддерживаются только файлы в WAV формате</small>
                </form>
            </div>
            
        </div>
    </div>
{% endblock %}